
states = {
    'P1' : 'Paraná',
    'A1' : 'Acre',
    'A2' : 'Alagoas',
    'A3' : 'Amapá',
    'A4' : 'Amazonas',
    'B1' : 'Bahia',
    'C1' : 'Ceará',
    'D1' : 'Distrito Federal',
    'E1' : 'Espírito Santo',
    'G1' : 'Goiás',
    'M1' : 'Maranhão',
    'M2' : 'Mato Grosso',
    'M3' : 'Mato Grosso do Sul',
    'M4' : 'Minas Gerais',
    'P2' : 'Pará',
    'P3' : 'Paraíba',
    'P4' : 'Pernambuco',
    'P5' : 'Piauí',
    'R1' : 'Rio de Janeiro',
    'R2' : 'Rio Grande do Norte',
    'R3' : 'Rio Grande do Sul',
    'R4' : 'Rondônia',
    'R5' : 'Roraima',
    'S1' : 'Santa Catarina',
    'S2' : 'São Paulo',
    'S3' : 'Sergipe',
    'T1' : 'Tocantins',
	"XX" : 'Estrangeiro'
}